// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ontgtgdnuancwmzacqtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9udGd0Z2RudWFuY3dtemFjcXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTY5MjEsImV4cCI6MjA1OTQzMjkyMX0.02eTAXz4RC65HLhGc4uvRWTvoyeEWGN3-VWSITCx3Ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});